* Taller de Visibilidad Web

** Tecnologías

- Linux
- Git
- Nodejs
- Apache
- MariaDB
- Ngrok
- Gmail

** Instalación y configuración

Antes de iniciar, se debe asegurar que se tiene acceso de
administrador =root= en la máquina que se trabajará

#+BEGIN_SRC bash
  sudo apt update
  sudo apt install -y mariadb-server git apache2 nodejs npm gnupg2
  sudo systemctl start mariadb
  sudo systemctl start apache2
  sudo mysql_secure_installation
  ssh-keygen
#+END_SRC

En el último paso estableceremos la nueva contraseña de =root=,
eliminar las bases de datos por defecto y recargar los
privilegios. Para fines didácticos necesitamos crear dos carpetas:
=local= y =server=. Es momento de copiar nuestra llave pública
=id_rsa.pub=, para ello se debe ejecutar el comando:

#+BEGIN_SRC bash
cat ~/.ssh/id_rsa.pub
#+END_SRC

El contenido debe ser copiado y pegado en el prefil de github del
usuario, esta configuración se hace en este [[por medio de ][enlace]]. Antes de comenzar
a escribir código es necesario crear un repositorio y clonarlo:

#+BEGIN_SRC bash
mkdir local && cd local
git clone https://github.com/camachojua/TallerVisibilidad.git
#+END_SRC

De nuevo, por fines didácticos se añadirá al usuario en curso al grupo
=www-data=, con el fin de evitar problemas de permisos cuando se
intente modificar un archivo. Para ello debemos cambiarnos al
directorio de apache =/var/www/=, cambiar el grupo y usuario al que
pertenece el directorio (de =root= a =www-data=) y por último
agregaremos al usuario local al grupo =www-data=.

#+BEGIN_SRC bash
cd /var/www
newgrp www-data
sudo chown -R www-data:www-data .
sudo chmod 775 -R /var/www/
sudo usermod -a -G www-data usuario
#+END_SRC

Después de establecer los permisos hay que clonar el repositorio en la
carpeta =/var/www/html/=:

#+BEGIN_SRC bash
cd /var/www
sudo chmod -R 755 .
sudo chmod -R 755 html
git clone https://github.com/camachojua/TallerVisibilidad.git
#+END_SRC

Ahora hay que levantar un *webhook* en github, para iremos a este
 [[https://github.com/arturo8gll][perfil de github]], donde se encontrarán varios repositorios de esos se
 hará un *fork* a este [[al][repositorio]], al terminar se creará una copia de
 ese repositorio en tu perfil de github, posteriormente se clonará el
 repositorio usando ssh:

#+BEGIN_SRC bash
cd /var/www/html
git clone git@github.com:camachojua/vw-webhook.git
cd vw-webhook
#+END_SRC

El proyecto =vw-webhook= esta desarrollado en =node=, para poder
utilizarlo debemos ejecutar el comando:

#+BEGIN_SRC bash
npm install
#+END_SRC

El archivo =server.js= contiene el webhook necesario para lanzar un
trabajo por lo tanto se debe ejecutar, posteriormente se hará uso de
=ngrok= para publicar el puerto:

#+BEGIN_SRC bash
node server.js &
~/ngrok http 3000
#+END_SRC

Al ejecutar el último comando se nos regresa una url donde podemos
consultar nuestro servicio desde cualquier punto de interner, en este
ejemplo =ngrok= devolvió:

#+BEGIN_SRC bash
ngrok by @inconshreveable
(Ctrl+C to quit)
Session Status                online
Account                       Juan Alberto Camacho Bolaños (Plan: Free)
Version                       2.3.34
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://33756b11.ngrok.io -> http://localhost:3000
Forwarding                    https://33756b11.ngrok.io -> http://localhost:3000
#+END_SRC

Es momento de ir al repositorio que se creó [[https://github.com/camachojua/TallerVisibilidad.git][inicialmente]] y crear un
[[webhook][webhook]], insertamos el valor que nos devuelve =ngrok=:
=https://33756b11.ngrok.io/visibilidad= con el *content-type*
=application/json=, verificación de certificado habilitada y el tipo
de evento enviado como *push*, por último hay que dar clic en *add webhook*.

En la ventana de ejecución de =ngrok= debió aparecer un mensaje similar a:

#+BEGIN_SRC bash
HTTP Requests
-------------
POST /visibilidad              200 OK      
#+END_SRC

Ahora hay que editar el archivo =deploy.sh=, la primer línea debe
apuntar a la carpeta =~/TallerVisibilidad=

#+BEGIN_SRC bash
cd ~/TallerVisibilidad

echo "Pulling from Master"

git pull origin master

echo "Pulled successfully from master"
#+END_SRC

Y después ejecutamos el archivo =/var/www/html/vw-webhook/deploy.sh=
para comprobar su buen funcionamento. Una vez comprobado el
funcionamiento hay que cambiarnos al directorio que contiene el código
del primer repositorio que creamos (=TallerVisibilidad=):

#+BEGIN_SRC bash
cd ~/TallerVisibilidad/
mkdir local/dist
echo "<h1>UNAM</h1>" >> local/dist
#+END_SRC

Posteriormente revisaremos el estado del repositorio con =git status=
agregaremos los cambios realizados con =git add local= y
posteriormente haremos un commit con =git commit -m=. Cuando hagamos
un =git push= el webhook responderá apropiadamente y copiará la
información correspondiente dentro de la carpeta =/var/www/html= (vía
un =git pull=) de forma automática.

Para que todo se vea automático se modificará la configuración de
apache para que apunte al archivo =index.html= del repositorio
almacenado en =/var/www/html/TallerVisibilidad/=. Se modificará el
archivo =/etc/apache2/sites-enabled/000-default.conf=, el cambio será:

#+BEGIN_SRC diff
+ DocumentRoot /var/www/html/TallerVisibilidad/local/dist
- DocumentRoot /var/www/html
#+END_SRC

Por último se debe reiniciar el servidor apache:

#+BEGIN_SRC bash
systemctl restart apache2
#+END_SRC

Al recargar el servidor apache se debe mostrar una página de
bienvenida de la unam. Es tiempo de realizar más cambios al archivo
=index.html= del repositorio almacenado en la carpeta =/home=

*** Resumen

1. Existe una copia del código en el =/home= del usuario, típicamente
   aquí haces tu desarrollo.
2. Existe otra copia en =/var/www/= esta simula el ambiente del
   *servidor*, el código de esta copia se actualiza despúes de haber
   ejecutado un =commit= en la carpeta del punto anterior.
3. Se creó un =webhook= en github para reaccionar cada vez que se
   recibe un =commit=.
4. La carpeta =vw-webhook= contiene el archivo =deploy.sh= encargado
   de obtener la última versión del código automáticamente.

** Página estática

Para este punto haremos uso de un prepocesador de CSS para optimizar
nuestro tiempo y generar un archivo de estilos muy compactos que será
servido al cliente. El prepocesador utilizado en este repositorio será
[[https://webpack.js.org/][webpack]]. Otra dependencia nueva es [[https://pm2.keymetrics.io/][pm2]] es un programa similar a
=ngrok=, pm2 se encargará de administrar cualquier cosas que nuestra
aplicación necesite.

El primer paso de esta sección será generar el webhook para que
interactúe con =pm2=:

#+BEGIN_SRC bash
cd /var/www/html/vw-webhook
pm2 start server.js
pm2 list
#+END_SRC

Si todo sale bien después de ejecutar =pm2 list= debemos obtener una
salida similar a:

| App name | id | version | mode | pid | status | restart | uptime | cpu | mem    | user | watch    |
|----------+----+---------+------+-----+--------+---------+--------+-----+--------+------+----------|
| server   |  0 |   1.0.0 | fork | 541 | online |       0 | 0s     |  0% | 21.0MB | juan | disabled |

Procedemos a hacer fork a este [[|          |    |         |      |     |        |         |        |     |        |      |          |][repositorio]] y clonarlo en las carpetas:

#+BEGIN_SRC bash
cd ~
ogit clone git@github.com:camachojua/vw-api.git
/var/www/html
git clone git@github.com:camachojua/vw-api.git
#+END_SRC

Para que este programa pueda ejecutarse hay que ejecutar =npm install=

#+BEGIN_SRC bash
cd ~/vw-api
npm install
#+END_SRC

El API está definido en el archivo =server.js= se puede notar que hace
uso del puerto *3010* para servir.

#+BEGIN_SRC js
var express = require('express')
var app = express()
const path = require('path')
var bodyParser = require('body-parser')

var controllerRouter = require('./routes/tarea')

// parse application/x-www-form-urlencoded
app.use(bodyParser.urlencoded({ extended: false }))

// parse application/json
app.use(bodyParser.json())

app.set('views', path.join(__dirname, 'views'))
app.set('view engine', 'pug')
app.use(express.static(path.join(__dirname, 'public')))

app.use('/tarea', controllerRouter)

app.get('/', function (req, res) {
  res.render('index')
})

app.listen(3010, function () {
  console.log('Example app listening on port 3010!')
})
#+END_SRC

Posteriormente ejecutamos el programa con =node server.js=, finalmente
podemos ver el programa en acción si nos dirigimos a =localhost:3010=
en el navegador. Esta aplicación hace uso de una base de datos, por lo
que debemos crear una base para esta aplicación, para ello ejecutamos
=mysql -u root -p=:

#+BEGIN_SRC mysql
CREATE DATABASE visibilidad;

use visibilidad;

CREATE TABLE IF NOT EXISTS tarea(
  idTarea INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  descripcion varchar(80),
  importancia INTEGER
);
#+END_SRC

Una vez creada se debe llenar dicha base:

#+BEGIN_SRC mysql
INSERT INTO tarea VALUES(null,"Generar Reporte del año",1);
INSERT INTO tarea VALUES(null,"Planchar traje para boda",2);
INSERT INTO tarea VALUES(null,"Terminar tarea de calculo",3);
INSERT INTO tarea VALUES(null,"Comprar comida",1);
#+END_SRC

Las credenciales de ingreso a la base de datos se encuenta en
=connect/db.js=, antes de poder seguir se deben ajustar para que
concuerden con la instalación que realizaste. Para comprobar que todo
funciona correctamente se debe ejecutar =node server.js=, ir al
navegador (=localhost:3010/tarea=). El ejemplo debe regresar como
resultado:

#+BEGIN_SRC json
[{"idTarea":1,"descripcion":"Generar Reporte del año","importancia":1},
{"idTarea":2,"descripcion":"Planchar traje para boda","importancia":2},
{"idTarea":3,"descripcion":"Terminar tarea de calculo","importancia":3},
{"idTarea":4,"descripcion":"Comprar comida","importancia":1}]
#+END_SRC


** Página dinámica


